theme: minima
title: My Test Project
author: Nikolozi
email: nikolozkacharava@domain.com
description: > # this means to ignore newlines until "baseurl:"
 here goes my descripition for this blalala

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
